# Copyright (C) 2015-2016 Libre Informatique
#
# This file is licenced under the GNU GPL v3.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Librinfo\SonataSyliusUserBundle\Entity\SonataUser:
    type: mappedSuperclass
    table: librinfo_sonata_user
    fields:
        firstName:
            type: string
            length: 255
            nullable: true
        lastName:
            type: string
            length: 255
            nullable: true
        localeCode:
            type: string
            length: 12